export const SEED_DATA = [
  { id: 'mkbhd', title: 'MKBHD', subscriberCount: 19000000, fairScore: 9.6, sentiment: 'Highly respected tech reviewer, universally trusted.' },
  { id: 'veritasium', title: 'Veritasium', subscriberCount: 15300000, fairScore: 9.8, sentiment: 'Exceptional educational value, massive external respect.' },
  { id: 'mrbeast', title: 'MrBeast', subscriberCount: 300000000, fairScore: 8.5, sentiment: 'Massive reach. The pioneer of modern high-effort philanthropy and challenge content.' },
  { id: 'penguinz0', title: 'penguinz0', subscriberCount: 14700000, fairScore: 9.2, sentiment: 'Strong consistent community, well-regarded and honest commentator.' },
  { id: 'lemmino', title: 'LEMMiNO', subscriberCount: 5500000, fairScore: 9.9, sentiment: 'Rare uploads but god-tier reception across all of Reddit and social media.' },
  { id: 'tom-scott', title: 'Tom Scott', subscriberCount: 6400000, fairScore: 9.8, sentiment: 'Universal acclaim for integrity and educational focus.' },
  { id: 'markiplier', title: 'Markiplier', subscriberCount: 36000000, fairScore: 9.4, sentiment: 'Very healthy community, largely avoiding drama with good engagement.' },
  { id: 'kurzgesagt', title: 'Kurzgesagt', subscriberCount: 22000000, fairScore: 9.8, sentiment: 'Globally adored educational content with immense production value.' },
  { id: 'cgp-grey', title: 'CGP Grey', subscriberCount: 6000000, fairScore: 9.6, sentiment: 'Highly respected veteran of educational YouTube.' },
  { id: 'defunctland', title: 'Defunctland', subscriberCount: 1900000, fairScore: 9.9, sentiment: 'Documentary mastery; adored by critics and fans alike.' },
  { id: 'videogamedunkey', title: 'videogamedunkey', subscriberCount: 7500000, fairScore: 9.5, sentiment: 'Highly trusted game reviewer, strongly meme-aligned community.' },
  { id: 'smartereveryday', title: 'SmarterEveryDay', subscriberCount: 11000000, fairScore: 9.7, sentiment: 'Passionate engineering and science content with a deeply loyal following.' },
  { id: 'mark-rober', title: 'Mark Rober', subscriberCount: 50000000, fairScore: 9.6, sentiment: 'Brilliant engineering entertainment; widely loved across all internet demographics.' },
  { id: 'vsauce', title: 'Vsauce', subscriberCount: 22000000, fairScore: 9.8, sentiment: 'Legendary science/philosophy channel that defined an era of YouTube.' },
  { id: 'jacksepticeye', title: 'Jacksepticeye', subscriberCount: 30000000, fairScore: 9.1, sentiment: 'Positive, energetic, and maintains a highly devoted fanbase.' },
  { id: 'dantdm', title: 'DanTDM', subscriberCount: 28000000, fairScore: 9.3, sentiment: 'Childhood staple for millions, respected for staying completely controversy-free.' },
  { id: 'ryan-trahan', title: 'Ryan Trahan', subscriberCount: 15000000, fairScore: 9.4, sentiment: 'Breathed new life into challenge content with immense heart and authenticity.' },
  { id: 'sidemen', title: 'Sidemen', subscriberCount: 20000000, fairScore: 8.8, sentiment: 'The pinnacle of group content on YouTube, evolving gracefully over years.' },
  { id: 'technoblade', title: 'Technoblade', subscriberCount: 16000000, fairScore: 10.0, sentiment: 'Universally beloved Minecraft legend whose legacy remains deeply honored.' },
  { id: 'noodle', title: 'Noodle', subscriberCount: 2100000, fairScore: 9.5, sentiment: 'Incredible animation quality paired with hilarious, insightful commentary.' },
  { id: 'internet-historian', title: 'Internet Historian', subscriberCount: 4000000, fairScore: 8.9, sentiment: 'Masterful storytelling of internet folklore with unparalleled comedic editing.' },
  { id: 'wendigoon', title: 'Wendigoon', subscriberCount: 3500000, fairScore: 9.4, sentiment: 'Deep dive horror and conspiracy coverage delivered with soothing respect.' },
  { id: 'summoning-salt', title: 'Summoning Salt', subscriberCount: 1500000, fairScore: 9.8, sentiment: 'The gold standard for speedrun documentary content. Impeccable score.' },
  { id: 'scott-the-woz', title: 'Scott The Woz', subscriberCount: 3000000, fairScore: 9.6, sentiment: 'Consistent, nostalgic, high-quality Nintendo and gaming retrospectives.' },
  { id: 'someordinarygamers', title: 'SomeOrdinaryGamers', subscriberCount: 3500000, fairScore: 9.2, sentiment: 'Trusted voice in cybersecurity, anti-scam, and deep web exploration.' },
  { id: 'coryxkenshin', title: 'CoryxKenshin', subscriberCount: 17000000, fairScore: 9.7, sentiment: 'Wholesome, overwhelmingly beloved gaming channel. The definition of a loyal fanbase.' },
  { id: 'dashiegames', title: 'DashieGames', subscriberCount: 6500000, fairScore: 9.1, sentiment: 'A pillar of YouTube gaming with legendary chaotic energy.' },
  { id: 'mr-weebl', title: 'Mr Weebl', subscriberCount: 1000000, fairScore: 8.5, sentiment: 'A classic animator from the Flash era, deeply nostalgic for older viewers.' },
  { id: 'michael-reeves', title: 'Michael Reeves', subscriberCount: 7500000, fairScore: 9.5, sentiment: 'Chaotic coding and engineering that perfectly captures internet humor.' },
  { id: 'william-osman', title: 'William Osman', subscriberCount: 3000000, fairScore: 9.3, sentiment: 'Authentic maker channel that embraces failure and comedy seamlessly.' },
  { id: 'allen-pan', title: 'Allen Pan', subscriberCount: 2000000, fairScore: 9.2, sentiment: 'Brilliant engineering focused on bringing pop culture items to life.' },
  { id: 'colin-furze', title: 'Colin Furze', subscriberCount: 13000000, fairScore: 9.6, sentiment: 'A literal mad scientist in a shed; unparalleled extreme builder.' },
  { id: 'stuffmadehere', title: 'StuffMadeHere', subscriberCount: 4500000, fairScore: 9.8, sentiment: 'Engineering perfectionist pushing the boundaries of what a single creator can build.' },
  { id: 'i-did-a-thing', title: 'I Did A Thing', subscriberCount: 5000000, fairScore: 9.3, sentiment: 'Australian chaotic crafting with a surprisingly deep political/social undertone.' },
  { id: 'boy-boy', title: 'Boy Boy', subscriberCount: 1500000, fairScore: 9.0, sentiment: 'Incredibly daring and insightful journalistic comedy.' },
  { id: 'cold-ones', title: 'Cold Ones', subscriberCount: 4000000, fairScore: 8.8, sentiment: 'Absolute chaotic entertainment; an evolution of the FilthyFrank era alumni.' },
  { id: 'danny-gonzalez', title: 'Danny Gonzalez', subscriberCount: 6500000, fairScore: 9.5, sentiment: 'Consistently witty commentary and wildly creative original songs.' },
  { id: 'drew-gooden', title: 'Drew Gooden', subscriberCount: 4500000, fairScore: 9.5, sentiment: 'High-effort, extremely sharp commentary on internet culture and bad products.' },
  { id: 'kurtis-conner', title: 'Kurtis Conner', subscriberCount: 5000000, fairScore: 9.4, sentiment: 'Mayor of Kurtistown; inclusive, hilarious, and thoughtful commentary.' },
  { id: 'eddy-burback', title: 'Eddy Burback', subscriberCount: 1500000, fairScore: 9.6, sentiment: 'Raises the bar for internet documentaries and dedicated deep dives.' },
  { id: 'gus-johnson', title: 'Gus Johnson', subscriberCount: 3000000, fairScore: 8.0, sentiment: 'Classic sketch comedy that captures absurd realities perfectly.' },
  { id: 'nakeyjakey', title: 'NakeyJakey', subscriberCount: 2000000, fairScore: 9.7, sentiment: 'The ultimate "sitting on an exercise ball talking about nostalgic games" vibe.' },
  { id: 'internet-comment-etiquette', title: 'Internet Comment Etiquette', subscriberCount: 1200000, fairScore: 9.4, sentiment: 'Pioneered a unique style of satirical deep-web trolling.' },
  { id: 'general-sam', title: 'General Sam', subscriberCount: 1500000, fairScore: 8.7, sentiment: 'Unhinged gaming content that captures the real spirit of laughing with friends.' },
  { id: 'welyn', title: 'Welyn', subscriberCount: 3000000, fairScore: 9.0, sentiment: 'The undisputed storyteller of Rust; creates cinematic narratives from gameplay.' },
  { id: 'ludwig', title: 'Ludwig', subscriberCount: 6000000, fairScore: 8.9, sentiment: 'Innovator in livestreaming who heavily curates community interaction.' },
  { id: 'sykkuno', title: 'Sykkuno', subscriberCount: 2900000, fairScore: 8.6, sentiment: 'Wholesome icon of the pandemic-era gaming boom.' },
  { id: 'corpse-husband', title: 'Corpse Husband', subscriberCount: 7000000, fairScore: 8.8, sentiment: 'Mysterious, deeply supportive community rallying behind his music and gaming.' },
  { id: 'jaiden-animations', title: 'Jaiden Animations', subscriberCount: 13000000, fairScore: 9.6, sentiment: 'One of the hardest working and most authentic animators on the platform.' },
  { id: 'theodd1sout', title: 'TheOdd1sOut', subscriberCount: 19000000, fairScore: 8.9, sentiment: 'Highly successful, family-friendly animation titan.' },
  { id: 'domics', title: 'Domics', subscriberCount: 7500000, fairScore: 9.1, sentiment: 'A founding pillar of the YouTube storytime animation era.' },
  { id: 'berleezy', title: 'Berleezy', subscriberCount: 4000000, fairScore: 9.2, sentiment: 'Immense energy, deeply loved by his community.' },
  { id: 'supermega', title: 'SuperMega', subscriberCount: 1000000, fairScore: 8.5, sentiment: 'The quintessential "two guys on a couch playing games" podcast and let\'s play.' },
  { id: 'game-grumps', title: 'Game Grumps', subscriberCount: 5500000, fairScore: 8.7, sentiment: 'Absolute stalwarts of the Let\'s Play genre running for over a decade.' },
  { id: 'jontron', title: 'JonTron', subscriberCount: 6500000, fairScore: 8.6, sentiment: 'Cinematic game reviews that birthed a thousand internet memes.' },
  { id: 'pbgs', title: 'PeanutButterGamer', subscriberCount: 2000000, fairScore: 9.0, sentiment: 'Completely wholesome, classic, nostalgic Nintendo hacking and reviews.' },
  { id: 'caddicarus', title: 'Caddicarus', subscriberCount: 1500000, fairScore: 9.4, sentiment: 'High-octane, chaotic, incredibly detailed British gaming retrospectives.' },
  { id: 'brian-david-gilbert', title: 'Brian David Gilbert', subscriberCount: 1200000, fairScore: 9.8, sentiment: 'The absolute pinnacle of unhinged, theatrical video game lore analysis.' },
  { id: 'jerma985', title: 'Jerma985', subscriberCount: 1500000, fairScore: 9.9, sentiment: 'An actual alien; the most universally loved and creatively ambitious streamer.' },
  { id: 'dougdoug', title: 'DougDoug', subscriberCount: 3000000, fairScore: 9.7, sentiment: 'Explains things with food and ruins video games with code. Chat is the main character.' },
  { id: 'pointcrow', title: 'PointCrow', subscriberCount: 1800000, fairScore: 9.2, sentiment: 'Incredibly charismatic Nintendo speedrunner and mod challenger.' },
  { id: 'smallant', title: 'SmallAnt', subscriberCount: 3500000, fairScore: 9.3, sentiment: 'Brought highly technical speedrunning challenges to the extreme mainstream.' },
  { id: 'rtgame', title: 'RTGame', subscriberCount: 3000000, fairScore: 9.4, sentiment: 'Irish chaos incarnate; destroying video game ecosystems for our amusement.' },
  { id: 'callmekevin', title: 'CallMeKevin', subscriberCount: 3500000, fairScore: 9.5, sentiment: 'Cult leader of Jim Pickens; relentlessly plays games "wrong" in the best way.' },
  { id: 'spiffingbrit', title: 'The Spiffing Brit', subscriberCount: 3500000, fairScore: 9.3, sentiment: 'Breaks every game economically with Yorkeshire Tea in hand.' },
  { id: 'lets-game-it-out', title: 'Let\'s Game It Out', subscriberCount: 6000000, fairScore: 9.5, sentiment: 'Tests the absolute limits of sandbox games until the framerate dies.' },
  { id: 'captainsparklez', title: 'CaptainSparklez', subscriberCount: 11000000, fairScore: 8.9, sentiment: 'Minecraft royalty. Responsible for the internet\'s biggest childhood anthems.' },
  { id: 'ethoslab', title: 'EthosLab', subscriberCount: 2500000, fairScore: 10.0, sentiment: 'The YouTuber that your favorite YouTubers watch. Unmatched integrity and skill.' },
  { id: 'grian', title: 'Grian', subscriberCount: 8500000, fairScore: 9.6, sentiment: 'The absolute master of Minecraft building and hermitcraft chaos.' },
  { id: 'mumbojumbo', title: 'Mumbo Jumbo', subscriberCount: 9500000, fairScore: 9.5, sentiment: 'Redstone genius wrapped in extreme politeness.' },
  { id: 'tommyinnit', title: 'TommyInnit', subscriberCount: 15000000, fairScore: 8.2, sentiment: 'Hyperactive face of modern Minecraft, transitioned brilliantly into IRL comedy.' },
  { id: 'philza', title: 'Ph1LzA', subscriberCount: 3500000, fairScore: 9.1, sentiment: 'The creator of Minecraft Hardcore culture.' },
  { id: 'fundy', title: 'Fundy', subscriberCount: 4500000, fairScore: 9.0, sentiment: 'Creates absolutely impossible mods and executes them brilliantly.' },
  { id: 'bblocks', title: 'BBlocks', subscriberCount: 1500000, fairScore: 9.3, sentiment: 'Unbelievably precise and creative Minecraft cinematic building.' },
  { id: 'tierzoo', title: 'TierZoo', subscriberCount: 3500000, fairScore: 9.6, sentiment: 'Analyzes real-world biology through the lens of a competitive video game meta.' },
  { id: 'minutearth', title: 'MinuteEarth', subscriberCount: 2500000, fairScore: 9.4, sentiment: 'Bite-sized, highly accessible scientific truths.' },
  { id: 'standupmaths', title: 'Stand-up Maths', subscriberCount: 1200000, fairScore: 9.5, sentiment: 'Matt Parker makes extreme mathematics deeply hilarious.' },
  { id: 'numberphile', title: 'Numberphile', subscriberCount: 4500000, fairScore: 9.6, sentiment: 'The gold standard for interviews with brilliant mathematicians.' },
  { id: 'computerphile', title: 'Computerphile', subscriberCount: 2500000, fairScore: 9.5, sentiment: 'In-depth, no-nonsense computer science explanations.' },
  { id: 'tommy-edison', title: 'Tommy Edison Experience', subscriberCount: 700000, fairScore: 9.8, sentiment: 'Beautifully positive outlook on life from a blind creator.' },
  { id: 'simone-giertz', title: 'Simone Giertz', subscriberCount: 2500000, fairScore: 9.7, sentiment: 'The queen of shitty robots transitioned into an incredible designer and builder.' },
  { id: 'stevemre1989', title: 'Steve1989MREInfo', subscriberCount: 2000000, fairScore: 9.9, sentiment: 'Nice. Let\'s get this out onto a tray. Unrivaled historical artifact tasting.' },
  { id: 'atomic-shrimp', title: 'Atomic Shrimp', subscriberCount: 1200000, fairScore: 9.6, sentiment: 'Foraging, scam baiting, and weird experiments. Pure authenticity.' },
  { id: 'geowizard', title: 'GeoWizard', subscriberCount: 1500000, fairScore: 9.5, sentiment: 'Straight line missions that capture the pure essence of human adventure limit-testing.' },
  { id: 'shiey', title: 'shiey', subscriberCount: 3000000, fairScore: 9.7, sentiment: 'Illegal train surfing and urban exploration shot flawlessly with zen commentary.' },
  { id: 'superwog', title: 'Superwog', subscriberCount: 3000000, fairScore: 8.8, sentiment: 'Iconic Australian sketch comedy that refuses to pull any punches.' },
  { id: 'mrfudgemonkeyz', title: 'MrFudgeMonkeyz', subscriberCount: 1500000, fairScore: 9.4, sentiment: 'The absolute master of Annoying Villagers Minecraft animation.' },
  { id: 'alanzoka', title: 'Alanzoka', subscriberCount: 6500000, fairScore: 9.3, sentiment: 'Extremely popular and beloved Brazilian gaming creator.' },
  { id: 'patterrz', title: 'Patterrz', subscriberCount: 500000, fairScore: 8.5, sentiment: 'Nostalgic Pokémon challenge runner with great community retention.' },
  { id: 'pokemon-challenges', title: 'PokemonChallenges', subscriberCount: 1000000, fairScore: 9.1, sentiment: 'The face of hardcore Nuzlocking. Brutal but educational.' },
  { id: 'alpharad', title: 'Alpharad', subscriberCount: 3500000, fairScore: 9.2, sentiment: 'The king of "Forward Aerial" and deeply embedded Smash Bros culture.' },
  { id: 'jacksfilms', title: 'jacksfilms', subscriberCount: 5000000, fairScore: 9.5, sentiment: 'Over 15 years on the platform, continuously evolving and surviving.' },
  { id: 'mr-fruit', title: 'Mr. Fruit', subscriberCount: 2000000, fairScore: 9.2, sentiment: 'Wholesome gaming, destiny veteran, deeply loyal community.' },
  { id: 'datto', title: 'Datto', subscriberCount: 1200000, fairScore: 9.4, sentiment: 'The mathematical bedrock of the Destiny 2 community.' },
  { id: 'byf', title: 'My name is Byf', subscriberCount: 1200000, fairScore: 9.6, sentiment: 'The Lore Daddy. Creates movie-length deep dives into video game lore.' },
  { id: 'vaatividya', title: 'VaatiVidya', subscriberCount: 3500000, fairScore: 9.8, sentiment: 'The absolute voice of Soulsborne lore. Stunning cinematic production.' },
  { id: 'iron-pineapple', title: 'Iron Pineapple', subscriberCount: 1500000, fairScore: 9.4, sentiment: 'Weird soulslike reviews that are always incredibly entertaining.' },
  { id: 'zanny', title: 'Zanny', subscriberCount: 2000000, fairScore: 9.2, sentiment: 'Loud, hyper-edited gaming comedy that hits incredibly hard.' },
  { id: 'bismix', title: 'Bismix', subscriberCount: 1000000, fairScore: 8.9, sentiment: 'Creates pitch-perfect sketch scenarios based entirely inside video game logics.' },
];
